eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: spring-cloud-ribbon
  zipkin:
    base-url: http://localhost:9411
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"