server:
  port: ${random.int[8763,8800]}
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

